# Generated by Django 2.1.7 on 2019-04-17 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedpoint',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedpoint',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedpoint',
            name='altitude_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routeline',
            name='color',
            field=models.CharField(default='#a0a0a0', max_length=7, validators=[django.core.validators.RegexValidator('#[a-zA-Z0-9]{6}')]),
        ),
    ]
